# Site settings
title: Cyrus Vandrevala
email: cyrus.vandrevala@gmail.com
url: https://cmvandrevala.github.io
description: "The personal website of Cyrus Vandrevala."

# Contact form: comment the line below if you want to stick with the default PHP contact form
#contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Cyrus Vandrevala
  location: Location
  social: You Can Find Me On...
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cmvandrevala
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/cmvandrevala

# Postal address (add as many lines as necessary)
address:
  - line: Purdue University
  - line: Department of Physics and Astronomy
  - line: 525 Northwestern Avenue
  - line: West Lafayette, IN 47907

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
